services:
  api-solid-pg-default:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
     - POSTGRESQL_USERNAME=docker
     - POSTGRESQL_PASSWORD=docker
     - POSTGRESQL_DATABASE=apisoliddefault
